default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] || '127.0.0.1' %>
  username: eic_development
  password: eic_development
  pool: 5

development:
  <<: *default
  database: eic_app

test:
  <<: *default
  database: eic_app_test
  min_messages: warning

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  checkout_timeout: <%= ENV["AR_CONNECTION_TIMEOUT"] || 5 %>